feat: adds checks to the ecr scripts (#7)

diff --git a/scripts/utils b/scripts/utils
--- a/scripts/utils
+++ b/scripts/utils
@@ -20,3 +20,10 @@ function check_eksctl_installed {
     exit 1
   fi
 }
+
+function check_docker_installed {
+  if ! command -v docker &> /dev/null; then
+    echo "Docker could not be found. Please install it first. https://www.docker.com/"
+    exit 1
+  fi
+}
